M48
; DRILL file {KiCad 9.0.0} date 2025-06-02T11:47:32-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-02T11:47:32-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X4.7037Y-3.1324
T2
X3.8978Y-3.0579
X5.4755Y-3.2788
M30
